permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 陈园军
  email: chen.nianxin@gmail.com
  link: http://comeon0r.github.io/
  weibo: http://weibo.com/chenyuanjun/
  github: http://github.com/chenyj

# 站点信息
title: 陈园军(Chen Yuanjun)的博客 
description: 陈园军的博客
url: http://comeon0r.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/myself.png
favicon: /public/img/myself.png

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: chenyuanjun

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: Tags
  about: About
  newest: Newest
  archive: Archive
  content: Content
