permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Yuanjun Chen
  email: chen.nianxin@gmail.com
  link: http://comeon0r.github.io
  weibo: http://weibo.com/1594928347/profile?topnav=1&wvr=6
  github: http://github.com/comeon0r
  linkedin: www.linkedin.com/in/chenyj

# 站点信息
title: 陈园军(Yuanjun Chen)的博客
description: My personal blog
url: http://comeon0r.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/myself.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: painterlin

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: Tags
  about: About
  newest: Newest
  archive: Archive